/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package _TEAM4_WEB_PROJECT_GRADLE;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
