/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package _TEAM4_WEB_PROJECT_GRADLE;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod());
    }
}
